package com.bigbratan.emulair.services

import com.bigbratan.emulair.models.Game
import javax.inject.Inject
import javax.inject.Singleton

@Singleton
class GamesService @Inject constructor(
) {
    fun fetchGames(): List<Game> {
        return dummyGames
    }

    private val dummyGames = listOf(
        Game(
            id = 1,
            systemId = 1,
            fullTitle = "Castlevania: Symphony of the Night (Europe) (En,Fr,It)",
            displayTitle = "Castlevania: Symphony of the Night",
            developer = "Konami Computer Entertainment Tokyo",
            publisher = "Konami",
            genre = "Adventure",
            releaseDate = 99999999999,
            region = "Europe",
            lastIndexedAt = 99999,
            fileName = "file",
            fileUri = "file.iso",
        ),
        Game(
            id = 2,
            systemId = 1,
            fullTitle = "Need for Speed: Most Wanted (2005) (USA) (En,Es)",
            displayTitle = "Need for Speed: Most Wanted (2005)",
            developer = "Electronic Arts Canada",
            publisher = "Electronic Arts",
            genre = "Racing",
            releaseDate = 99999999999,
            region = "USA",
            lastIndexedAt = 99999,
            fileName = "file",
            fileUri = "file.iso",
        ),
        Game(
            id = 3,
            systemId = 2,
            fullTitle = "Metal Gear Solid (Asia) (En,Jp,Kr,Cn)",
            displayTitle = "Metal Gear Solid",
            developer = "Konami",
            publisher = "Konami",
            genre = "Action",
            releaseDate = 99999999999,
            region = "Asia",
            lastIndexedAt = 99999,
            fileName = "file",
            fileUri = "file.iso",
        ),
        Game(
            id = 4,
            systemId = 3,
            fullTitle = "God of War (USA) (En,Fr,It)",
            displayTitle = "God of War",
            developer = "Santa Monica Studio",
            publisher = "Sony Computer Entertainment",
            genre = "Action",
            releaseDate = 99999999999,
            region = "USA",
            lastIndexedAt = 99999,
            fileName = "file",
            fileUri = "file.iso",
        ),
        Game(
            id = 5,
            systemId = 2,
            fullTitle = "Assassin's Creed (USA) (En,Fr,It)",
            displayTitle = "Assassin's Creed",
            developer = "Ubisoft Montreal",
            publisher = "Ubisoft",
            genre = "Action",
            releaseDate = 99999999999,
            region = "USA",
            lastIndexedAt = 99999,
            fileName = "file",
            fileUri = "file.iso",
        ),
        Game(
            id = 6,
            systemId = 1,
            fullTitle = "Final Fantasy VII (USA) (En,Fr,It)",
            displayTitle = "Final Fantasy VII",
            developer = "Square",
            publisher = "Sony Computer Entertainment",
            genre = "RPG",
            releaseDate = 99999999999,
            region = "USA",
            lastIndexedAt = 99999,
            fileName = "file",
            fileUri = "file.iso",
        ),
        Game(
            id = 7,
            systemId = 4,
            fullTitle = "The Legend of Zelda: Ocarina of Time (USA) (En,Fr,It)",
            displayTitle = "The Legend of Zelda: Ocarina of Time",
            developer = "Nintendo EAD",
            publisher = "Nintendo",
            genre = "Adventure",
            releaseDate = 99999999999,
            region = "USA",
            lastIndexedAt = 99999,
            fileName = "file",
            fileUri = "file.iso",
        ),
        Game(
            id = 8,
            systemId = 4,
            fullTitle = "Super Mario Bros. (USA) (En,Fr,It)",
            displayTitle = "Super Mario Bros.",
            developer = "Nintendo R&D4",
            publisher = "Nintendo",
            genre = "Adventure",
            releaseDate = 99999999999,
            region = "USA",
            lastIndexedAt = 99999,
            fileName = "file",
            fileUri = "file.iso",
        ),
        Game(
            id = 9,
            systemId = 4,
            fullTitle = "Silent Hill (USA) (En,Fr,It)",
            displayTitle = "Silent Hill",
            developer = "Team Silent",
            publisher = "Konami",
            genre = "Action",
            releaseDate = 99999999999,
            region = "USA",
            lastIndexedAt = 99999,
            fileName = "file",
            fileUri = "file.iso",
        ),
        Game(
            id = 10,
            systemId = 4,
            fullTitle = "Resident Evil 2 (USA) (En,Fr,It)",
            displayTitle = "Resident Evil 2",
            developer = "Capcom",
            publisher = "Capcom",
            genre = "Action",
            releaseDate = 99999999999,
            region = "USA",
            lastIndexedAt = 99999,
            fileName = "file",
            fileUri = "file.iso",
        ),
        Game(
            id = 11,
            systemId = 2,
            fullTitle = "The Elder Scrolls V: Skyrim (USA) (En,Fr,It)",
            displayTitle = "The Elder Scrolls V: Skyrim",
            developer = "Bethesda Game Studios",
            publisher = "Bethesda Softworks",
            genre = "RPG",
            releaseDate = 99999999999,
            region = "USA",
            lastIndexedAt = 99999,
            fileName = "file",
            fileUri = "file.iso",
        ),
        Game(
            id = 12,
            systemId = 5,
            fullTitle = "Doom (USA) (En,Fr,It)",
            displayTitle = "Doom",
            developer = "id Software",
            publisher = "id Software",
            genre = "Action",
            releaseDate = 99999999999,
            region = "USA",
            lastIndexedAt = 99999,
            fileName = "file",
            fileUri = "file.iso",
        ),
        Game(
            id = 13,
            systemId = 1,
            fullTitle = "Half-Life (USA) (En,Fr,It)",
            displayTitle = "Half-Life",
            developer = "Valve",
            publisher = "Sierra Studios",
            genre = "Action",
            releaseDate = 99999999999,
            region = "USA",
            lastIndexedAt = 99999,
            fileName = "file",
            fileUri = "file.iso",
        ),
        Game(
            id = 14,
            systemId = 6,
            fullTitle = "Grand Theft Auto III (USA) (En,Fr,It)",
            displayTitle = "Grand Theft Auto III",
            developer = "DMA Design",
            publisher = "Rockstar Games",
            genre = "Action",
            releaseDate = 99999999999,
            region = "USA",
            lastIndexedAt = 99999,
            fileName = "file",
            fileUri = "file.iso",
        ),
        Game(
            id = 15,
            systemId = 4,
            fullTitle = "Minecraft (USA) (En,Fr,It)",
            displayTitle = "Minecraft",
            developer = "Mojang",
            publisher = "Mojang",
            genre = "Simulation",
            releaseDate = 99999999999,
            region = "USA",
            lastIndexedAt = 99999,
            fileName = "file",
            fileUri = "file.iso",
        ),
        Game(
            id = 16,
            systemId = 3,
            fullTitle = "Terraria (USA) (En,Fr,It)",
            displayTitle = "Terraria",
            developer = "Re-Logic",
            publisher = "Re-Logic",
            genre = "Simulation",
            releaseDate = 99999999999,
            region = "USA",
            lastIndexedAt = 99999,
            fileName = "file",
            fileUri = "file.iso",
        ),
        Game(
            id = 17,
            systemId = 3,
            fullTitle = "Hollowknight (USA) (En,Fr,It)",
            displayTitle = "Hollowknight",
            developer = "Team Cherry",
            publisher = "Team Cherry",
            genre = "Adventure",
            releaseDate = 99999999999,
            region = "USA",
            lastIndexedAt = 99999,
            fileName = "file",
            fileUri = "file.iso",
        )
    )
}